# Project 2: Data Import - Working with Web APIs and JSON (Movies Dataset)

In [1]:
import pandas as pd
import json

## Importing Data from JSON files

1. __Import__ the json files __blockbusters.json__, __blockbusters2.json__, __blockbusters3.json__ and load the datasets into Pandas DataFrames.

In [2]:
with open('blockbusters.json') as f:
    data = json.load(f)

In [3]:
df = pd.DataFrame(data)
df.head()

,title,id,revenue,genres,belongs_to_collection,runtime
0,Avengers: Endgame,299534,2797800564,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...","{'id': 86311, 'name': 'The Avengers Collection...",181
1,Avatar,19995,2787965087,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 87096, 'name': 'Avatar Collection', 'po...",162
2,Star Wars: The Force Awakens,140607,2068223624,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 10, 'name': 'Star Wars Collection', 'po...",136
3,Avengers: Infinity War,299536,2046239637,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...","{'id': 86311, 'name': 'The Avengers Collection...",149
4,Titanic,597,1845034188,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",None,194

In [4]:
df2 = pd.read_json('blockbusters.json')
df2.head()

,title,id,revenue,genres,belongs_to_collection,runtime
0,Avengers: Endgame,299534,2797800564,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...","{'id': 86311, 'name': 'The Avengers Collection...",181
1,Avatar,19995,2787965087,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 87096, 'name': 'Avatar Collection', 'po...",162
2,Star Wars: The Force Awakens,140607,2068223624,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 10, 'name': 'Star Wars Collection', 'po...",136
3,Avengers: Infinity War,299536,2046239637,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...","{'id': 86311, 'name': 'The Avengers Collection...",149
4,Titanic,597,1845034188,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",None,194

In [5]:
data

[{'title': 'Avengers: Endgame',
  'id': 299534,
  'revenue': 2797800564,
  'genres': [{'id': 12, 'name': 'Adventure'},
   {'id': 878, 'name': 'Science Fiction'},
   {'id': 28, 'name': 'Action'}],
  'belongs_to_collection': {'id': 86311,
   'name': 'The Avengers Collection',
   'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
   'backdrop_path': '/zuW6fOiusv4X9nnW3paHGfXcSll.jpg'},
  'runtime': 181},
 {'title': 'Avatar',
  'id': 19995,
  'revenue': 2787965087,
  'genres': [{'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 14, 'name': 'Fantasy'},
   {'id': 878, 'name': 'Science Fiction'}],
  'belongs_to_collection': {'id': 87096,
   'name': 'Avatar Collection',
   'poster_path': '/nslJVsO58Etqkk17oXMuVK4gNOF.jpg',
   'backdrop_path': '/8nCr9W7sKus2q9PLbYsnT7iCkuT.jpg'},
  'runtime': 162},
 {'title': 'Star Wars: The Force Awakens',
  'id': 140607,
  'revenue': 2068223624,
  'genres': [{'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 878, 'name': 'Science Fiction'},
   {'id': 14, 'name': 'Fantasy'}],
  'belongs_to_collection': {'id': 10,
   'name': 'Star Wars Collection',
   'poster_path': '/iTQHKziZy9pAAY4hHEDCGPaOvFC.jpg',
   'backdrop_path': '/d8duYyyC9J5T825Hg7grmaabfxQ.jpg'},
  'runtime': 136},
 {'title': 'Avengers: Infinity War',
  'id': 299536,
  'revenue': 2046239637,
  'genres': [{'id': 12, 'name': 'Adventure'},
   {'id': 28, 'name': 'Action'},
   {'id': 878, 'name': 'Science Fiction'}],
  'belongs_to_collection': {'id': 86311,
   'name': 'The Avengers Collection',
   'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
   'backdrop_path': '/zuW6fOiusv4X9nnW3paHGfXcSll.jpg'},
  'runtime': 149},
 {'title': 'Titanic',
  'id': 597,
  'revenue': 1845034188,
  'genres': [{'id': 18, 'name': 'Drama'},
   {'id': 10749, 'name': 'Romance'},
   {'id': 53, 'name': 'Thriller'}],
  'belongs_to_collection': None,
  'runtime': 194},
 {'title': 'Jurassic World',
  'id': 135397,
  'revenue': 1671713208,
  'genres': [{'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 878, 'name': 'Science Fiction'},
   {'id': 53, 'name': 'Thriller'}],
  'belongs_to_collection': {'id': 328,
   'name': 'Jurassic Park Collection',
   'poster_path': '/qIm2nHXLpBBdMxi8dvfrnDkBUDh.jpg',
   'backdrop_path': '/pJjIH9QN0OkHFV9eue6XfRVnPkr.jpg'},
  'runtime': 124},
 {'title': 'The Lion King',
  'id': 420818,
  'revenue': 1656943394,
  'genres': [{'id': 12, 'name': 'Adventure'}, {'id': 10751, 'name': 'Family'}],
  'belongs_to_collection': None,
  'runtime': 118},
 {'title': 'The Avengers',
  'id': 24428,
  'revenue': 1519557910,
  'genres': [{'id': 878, 'name': 'Science Fiction'},
   {'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'}],
  'belongs_to_collection': {'id': 86311,
   'name': 'The Avengers Collection',
   'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
   'backdrop_path': '/zuW6fOiusv4X9nnW3paHGfXcSll.jpg'},
  'runtime': 143},
 {'title': 'Furious 7',
  'id': 168259,
  'revenue': 1506249360,
  'genres': [{'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}],
  'belongs_to_collection': {'id': 9485,
   'name': 'The Fast and the Furious Collection',
   'poster_path': '/uv63yAGg1zETAs1XQsOQpava87l.jpg',
   'backdrop_path': '/z5A5W3WYJc3UVEWljSGwdjDgQ0j.jpg'},
  'runtime': 137},
 {'title': 'Avengers: Age of Ultron',
  'id': 99861,
  'revenue': 1405403694,
  'genres': [{'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 878, 'name': 'Science Fiction'}],
  'belongs_to_collection': {'id': 86311,
   'name': 'The Avengers Collection',
   'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
   'backdrop_path': '/zuW6fOiusv4X9nnW3paHGfXcSll.jpg'},
  'runtime': 141},
 {'title': 'Black Panther',
  'id': 284054,
  'revenue': 1346739107,
  'genres': [{'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 14, 'name': 'Fantasy'},
   {'id': 878, 'name': 'Science Fiction'}],
  'belongs_to_collection': {'id': 529892,
   'name': 'Black Panther Collection',
   'poster_path': '/9ZSPIsxI3TZDgfg0Jzk0RZl4INg.jpg',
   'backdrop_path': '/1Jj7Frjjbewb6Q6dl6YXhL3kuvL.jpg'},
  'runtime': 134},
 {'title': 'Harry Potter and the Deathly Hallows: Part 2',
  'id': 12445,
  'revenue': 1341511219,
  'genres': [{'id': 14, 'name': 'Fantasy'}, {'id': 12, 'name': 'Adventure'}],
  'belongs_to_collection': {'id': 1241,
   'name': 'Harry Potter Collection',
   'poster_path': '/eVPs2Y0LyvTLZn6AP5Z6O2rtiGB.jpg',
   'backdrop_path': '/wfnMt6LGqYHcNyOfsuusw5lX3bL.jpg'},
  'runtime': 130},
 {'title': 'Star Wars: The Last Jedi',
  'id': 181808,
  'revenue': 1332539889,
  'genres': [{'id': 14, 'name': 'Fantasy'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 878, 'name': 'Science Fiction'},
   {'id': 28, 'name': 'Action'}],
  'belongs_to_collection': {'id': 10,
   'name': 'Star Wars Collection',
   'poster_path': '/iTQHKziZy9pAAY4hHEDCGPaOvFC.jpg',
   'backdrop_path': '/d8duYyyC9J5T825Hg7grmaabfxQ.jpg'},
  'runtime': 152},
 {'title': 'Frozen II',
  'id': 330457,
  'revenue': 1330764959,
  'genres': [{'id': 16, 'name': 'Animation'},
   {'id': 10751, 'name': 'Family'},
   {'id': 12, 'name': 'Adventure'}],
  'belongs_to_collection': {'id': 386382,
   'name': 'Frozen Collection',
   'poster_path': '/rpoXnE9UzCbjmINhxIi8bZF557B.jpg',
   'backdrop_path': '/vZiqhw6oFoMlHSneIdVip9rRou2.jpg'},
  'runtime': 104},
 {'title': 'Jurassic World: Fallen Kingdom',
  'id': 351286,
  'revenue': 1303459585,
  'genres': [{'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 878, 'name': 'Science Fiction'}],
  'belongs_to_collection': {'id': 328,
   'name': 'Jurassic Park Collection',
   'poster_path': '/qIm2nHXLpBBdMxi8dvfrnDkBUDh.jpg',
   'backdrop_path': '/pJjIH9QN0OkHFV9eue6XfRVnPkr.jpg'},
  'runtime': 129},
 {'title': 'Frozen',
  'id': 109445,
  'revenue': 1274219009,
  'genres': [{'id': 16, 'name': 'Animation'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 10751, 'name': 'Family'}],
  'belongs_to_collection': {'id': 386382,
   'name': 'Frozen Collection',
   'poster_path': '/rpoXnE9UzCbjmINhxIi8bZF557B.jpg',
   'backdrop_path': '/vZiqhw6oFoMlHSneIdVip9rRou2.jpg'},
  'runtime': 102},
 {'title': 'Beauty and the Beast',
  'id': 321612,
  'revenue': 1263521126,
  'genres': [{'id': 10751, 'name': 'Family'},
   {'id': 14, 'name': 'Fantasy'},
   {'id': 10749, 'name': 'Romance'}],
  'belongs_to_collection': None,
  'runtime': 129},
 {'title': 'Incredibles 2',
  'id': 260513,
  'revenue': 1241891456,
  'genres': [{'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 16, 'name': 'Animation'},
   {'id': 10751, 'name': 'Family'}],
  'belongs_to_collection': {'id': 468222,
   'name': 'The Incredibles Collection',
   'poster_path': '/l7GqbzkJwowYRIXAtUz2iCPi64a.jpg',
   'backdrop_path': '/9eDW2dVhnzPS2HvaRdK2OlAGaLq.jpg'},
  'runtime': 118}]

In [6]:
df['belongs_to_collection'][0]

{'id': 86311,
 'name': 'The Avengers Collection',
 'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
 'backdrop_path': '/zuW6fOiusv4X9nnW3paHGfXcSll.jpg'}

In [7]:
pd.json_normalize(data, sep= "_")

,title,id,revenue,genres,runtime,belongs_to_collection_id,belongs_to_collection_name,belongs_to_collection_poster_path,belongs_to_collection_backdrop_path,belongs_to_collection
0,Avengers: Endgame,299534,2797800564,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",181,86311.0,The Avengers Collection,/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg,/zuW6fOiusv4X9nnW3paHGfXcSll.jpg,NaN
1,Avatar,19995,2787965087,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",162,87096.0,Avatar Collection,/nslJVsO58Etqkk17oXMuVK4gNOF.jpg,/8nCr9W7sKus2q9PLbYsnT7iCkuT.jpg,NaN
2,Star Wars: The Force Awakens,140607,2068223624,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",136,10.0,Star Wars Collection,/iTQHKziZy9pAAY4hHEDCGPaOvFC.jpg,/d8duYyyC9J5T825Hg7grmaabfxQ.jpg,NaN
3,Avengers: Infinity War,299536,2046239637,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",149,86311.0,The Avengers Collection,/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg,/zuW6fOiusv4X9nnW3paHGfXcSll.jpg,NaN
4,Titanic,597,1845034188,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",194,NaN,NaN,NaN,NaN,NaN
5,Jurassic World,135397,1671713208,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",124,328.0,Jurassic Park Collection,/qIm2nHXLpBBdMxi8dvfrnDkBUDh.jpg,/pJjIH9QN0OkHFV9eue6XfRVnPkr.jpg,NaN
6,The Lion King,420818,1656943394,"[{'id': 12, 'name': 'Adventure'}, {'id': 10751...",118,NaN,NaN,NaN,NaN,NaN
7,The Avengers,24428,1519557910,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",143,86311.0,The Avengers Collection,/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg,/zuW6fOiusv4X9nnW3paHGfXcSll.jpg,NaN
8,Furious 7,168259,1506249360,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",137,9485.0,The Fast and the Furious Collection,/uv63yAGg1zETAs1XQsOQpava87l.jpg,/z5A5W3WYJc3UVEWljSGwdjDgQ0j.jpg,NaN
9,Avengers: Age of Ultron,99861,1405403694,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",141,86311.0,The Avengers Collection,/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg,/zuW6fOiusv4X9nnW3paHGfXcSll.jpg,NaN
10,Black Panther,284054,1346739107,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",134,529892.0,Black Panther Collection,/9ZSPIsxI3TZDgfg0Jzk0RZl4INg.jpg,/1Jj7Frjjbewb6Q6dl6YXhL3kuvL.jpg,NaN
11,Harry Potter and the Deathly Hallows: Part 2,12445,1341511219,"[{'id': 14, 'name': 'Fantasy'}, {'id': 12, 'na...",130,1241.0,Harry Potter Collection,/eVPs2Y0LyvTLZn6AP5Z6O2rtiGB.jpg,/wfnMt6LGqYHcNyOfsuusw5lX3bL.jpg,NaN
12,Star Wars: The Last Jedi,181808,1332539889,"[{'id': 14, 'name': 'Fantasy'}, {'id': 12, 'na...",152,10.0,Star Wars Collection,/iTQHKziZy9pAAY4hHEDCGPaOvFC.jpg,/d8duYyyC9J5T825Hg7grmaabfxQ.jpg,NaN
13,Frozen II,330457,1330764959,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",104,386382.0,Frozen Collection,/rpoXnE9UzCbjmINhxIi8bZF557B.jpg,/vZiqhw6oFoMlHSneIdVip9rRou2.jpg,NaN
14,Jurassic World: Fallen Kingdom,351286,1303459585,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",129,328.0,Jurassic Park Collection,/qIm2nHXLpBBdMxi8dvfrnDkBUDh.jpg,/pJjIH9QN0OkHFV9eue6XfRVnPkr.jpg,NaN
15,Frozen,109445,1274219009,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",102,386382.0,Frozen Collection,/rpoXnE9UzCbjmINhxIi8bZF557B.jpg,/vZiqhw6oFoMlHSneIdVip9rRou2.jpg,NaN
16,Beauty and the Beast,321612,1263521126,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",129,NaN,NaN,NaN,NaN,NaN
17,Incredibles 2,260513,1241891456,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",118,468222.0,The Incredibles Collection,/l7GqbzkJwowYRIXAtUz2iCPi64a.jpg,/9eDW2dVhnzPS2HvaRdK2OlAGaLq.jpg,NaN

In [8]:
pd.json_normalize(data,sep="_",record_path='genres',meta=['title','id'],record_prefix='genre_')

,genre_id,genre_name,title,id
0,12,Adventure,Avengers: Endgame,299534
1,878,Science Fiction,Avengers: Endgame,299534
2,28,Action,Avengers: Endgame,299534
3,28,Action,Avatar,19995
4,12,Adventure,Avatar,19995
5,14,Fantasy,Avatar,19995
6,878,Science Fiction,Avatar,19995
7,28,Action,Star Wars: The Force Awakens,140607
8,12,Adventure,Star Wars: The Force Awakens,140607
9,878,Science Fiction,Star Wars: The Force Awakens,140607
10,14,Fantasy,Star Wars: The Force Awakens,140607
11,12,Adventure,Avengers: Infinity War,299536
12,28,Action,Avengers: Infinity War,299536
13,878,Science Fiction,Avengers: Infinity War,299536
14,18,Drama,Titanic,597
15,10749,Romance,Titanic,597
16,53,Thriller,Titanic,597
17,28,Action,Jurassic World,135397
18,12,Adventure,Jurassic World,135397
19,878,Science Fiction,Jurassic World,135397
20,53,Thriller,Jurassic World,135397
21,12,Adventure,The Lion King,420818
22,10751,Family,The Lion King,420818
23,878,Science Fiction,The Avengers,24428
24,28,Action,The Avengers,24428
25,12,Adventure,The Avengers,24428
26,28,Action,Furious 7,168259
27,53,Thriller,Furious 7,168259
28,28,Action,Avengers: Age of Ultron,99861
29,12,Adventure,Avengers: Age of Ultron,99861
30,878,Science Fiction,Avengers: Age of Ultron,99861
31,28,Action,Black Panther,284054
32,12,Adventure,Black Panther,284054
33,14,Fantasy,Black Panther,284054
34,878,Science Fiction,Black Panther,284054
35,14,Fantasy,Harry Potter and the Deathly Hallows: Part 2,12445
36,12,Adventure,Harry Potter and the Deathly Hallows: Part 2,12445
37,14,Fantasy,Star Wars: The Last Jedi,181808
38,12,Adventure,Star Wars: The Last Jedi,181808
39,878,Science Fiction,Star Wars: The Last Jedi,181808
40,28,Action,Star Wars: The Last Jedi,181808
41,16,Animation,Frozen II,330457
42,10751,Family,Frozen II,330457
43,12,Adventure,Frozen II,330457
44,28,Action,Jurassic World: Fallen Kingdom,351286
45,12,Adventure,Jurassic World: Fallen Kingdom,351286
46,878,Science Fiction,Jurassic World: Fallen Kingdom,351286
47,16,Animation,Frozen,109445
48,12,Adventure,Frozen,109445
49,10751,Family,Frozen,109445
50,10751,Family,Beauty and the Beast,321612
51,14,Fantasy,Beauty and the Beast,321612
52,10749,Romance,Beauty and the Beast,321612
53,28,Action,Incredibles 2,260513
54,12,Adventure,Incredibles 2,260513
55,16,Animation,Incredibles 2,260513
56,10751,Family,Incredibles 2,260513

## Working with APIs and JSON (Part 1)

2. __Create an account__ on https://www.themoviedb.org/

In [9]:
import requests
pd.options.display.max_columns = 30

3. Get your personal __API Key__

In [10]:
api_key = 'api_key=20268708b9c332f1a7508360c73cc193'

4. __API-Request__ (movie module): Load all available information for the movie with __movie id = 140607__ into a Pandas DataFrame. <br> See https://developers.themoviedb.org/3/movies/get-movie-details for more information

In [11]:
movie_id = 140607
movie_api = "https://api.themoviedb.org/3/movie/{}?"
movie_api

'https://api.themoviedb.org/3/movie/{}?'

In [12]:
url = movie_api.format(movie_id) + api_key
url

'https://api.themoviedb.org/3/movie/140607?api_key=20268708b9c332f1a7508360c73cc193'

In [13]:
r = requests.get(url)
r

In [14]:
data = r.json()
data

{'adult': False,
 'backdrop_path': '/8BTsTfln4jlQrLXUBquXJ0ASQy9.jpg',
 'belongs_to_collection': {'id': 10,
  'name': 'Star Wars Collection',
  'poster_path': '/gq5Wi7i4SF3lo4HHkJasDV95xI9.jpg',
  'backdrop_path': '/d8duYyyC9J5T825Hg7grmaabfxQ.jpg'},
 'budget': 245000000,
 'genres': [{'id': 12, 'name': 'Adventure'},
  {'id': 28, 'name': 'Action'},
  {'id': 878, 'name': 'Science Fiction'},
  {'id': 14, 'name': 'Fantasy'}],
 'homepage': 'http://www.starwars.com/films/star-wars-episode-vii',
 'id': 140607,
 'imdb_id': 'tt2488496',
 'original_language': 'en',
 'original_title': 'Star Wars: The Force Awakens',
 'overview': 'Thirty years after defeating the Galactic Empire, Han Solo and his allies face a new threat from the evil Kylo Ren and his army of Stormtroopers.',
 'popularity': 64.888,
 'poster_path': '/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg',
 'production_companies': [{'id': 1,
   'logo_path': '/o86DbpburjxrqAzEDhXZcyE8pDb.png',
   'name': 'Lucasfilm Ltd.',
   'origin_country': 'US'},
  {'id': 11461,
   'logo_path': '/p9FoEt5shEKRWRKVIlvFaEmRnun.png',
   'name': 'Bad Robot',
   'origin_country': 'US'}],
 'production_countries': [{'iso_3166_1': 'US',
   'name': 'United States of America'}],
 'release_date': '2015-12-15',
 'revenue': 2068223624,
 'runtime': 136,
 'spoken_languages': [{'english_name': 'English',
   'iso_639_1': 'en',
   'name': 'English'}],
 'status': 'Released',
 'tagline': 'Every generation has a story.',
 'title': 'Star Wars: The Force Awakens',
 'video': False,
 'vote_average': 7.3,
 'vote_count': 17979}

In [15]:
final = pd.Series(data).to_frame().T
final

,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,/8BTsTfln4jlQrLXUBquXJ0ASQy9.jpg,"{'id': 10, 'name': 'Star Wars Collection', 'po...",245000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.starwars.com/films/star-wars-episod...,140607,tt2488496,en,Star Wars: The Force Awakens,Thirty years after defeating the Galactic Empi...,64.888,/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg,"[{'id': 1, 'logo_path': '/o86DbpburjxrqAzEDhXZ...","[{'iso_3166_1': 'US', 'name': 'United States o...",2015-12-15,2068223624,136,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Every generation has a story.,Star Wars: The Force Awakens,False,7.3,17979

In [16]:
pd.json_normalize(data,record_path='production_companies',meta='title')

,id,logo_path,name,origin_country,title
0,1,/o86DbpburjxrqAzEDhXZcyE8pDb.png,Lucasfilm Ltd.,US,Star Wars: The Force Awakens
1,11461,/p9FoEt5shEKRWRKVIlvFaEmRnun.png,Bad Robot,US,Star Wars: The Force Awakens

## Working with APIs and JSON (Part 2)

5. __API-Request__ (discover module): Load all movies with __release date between 2020-01-01 and 2020-02-29__ into a Pandas DataFrame. <br>
See https://www.themoviedb.org/documentation/api/discover and https://developers.themoviedb.org/3/discover/movie-discover for more information.

In [17]:
release = '&primary_release_date.gte=2020-01-01&primary_release_date.lte=2020-02-29'

In [18]:
movie_api2 = "https://api.themoviedb.org/3/discover/movie?"

In [19]:
url2 = movie_api2 + api_key + release
url2

'https://api.themoviedb.org/3/discover/movie?api_key=20268708b9c332f1a7508360c73cc193&primary_release_date.gte=2020-01-01&primary_release_date.lte=2020-02-29'

In [20]:
r2 = requests.get(url2)
r2

In [21]:
data2 = r2.json()
data2

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': None,
   'genre_ids': [18],
   'id': 677118,
   'original_language': 'ko',
   'original_title': '오르가즘 특강 2',
   'overview': 'Yuner, Liu Ren, and Zhou Xian are college girlfriends. They went to the holiday house to take pictures and swim together during the holidays. However, the three women soon became bored. Yuner came up with the idea of seducing men and happened to encounter a handsome sports car The passing Shi Yu and the senior asked the three women for directions, and Yuner handed over the phone number to the two men, and this extraordinary experience began …',
   'popularity': 91.246,
   'poster_path': '/gYSJi5avO0RmzrX9ZbKwM7ZMkng.jpg',
   'release_date': '2020-02-20',
   'title': 'Orgasm Lecture 2',
   'video': False,
   'vote_average': 10,
   'vote_count': 1},
  {'adult': False,
   'backdrop_path': '/stmYfCUGd8Iy6kAMBr6AmWqx8Bq.jpg',
   'genre_ids': [28, 878, 35, 10751],
   'id': 454626,
   'original_language': 'en',
   'original_title': 'Sonic the Hedgehog',
   'overview': 'Powered with incredible speed, Sonic The Hedgehog embraces his new home on Earth. That is, until Sonic sparks the attention of super-uncool evil genius Dr. Robotnik. Now it’s super-villain vs. super-sonic in an all-out race across the globe to stop Robotnik from using Sonic’s unique power for world domination.',
   'popularity': 71.239,
   'poster_path': '/aQvJ5WPzZgYVDrxLX4R6cLJCEaQ.jpg',
   'release_date': '2020-02-12',
   'title': 'Sonic the Hedgehog',
   'video': False,
   'vote_average': 7.4,
   'vote_count': 8658},
  {'adult': False,
   'backdrop_path': '/hRgQVdKh65nFiy2l7KhfWo7DHof.jpg',
   'genre_ids': [10751],
   'id': 520765,
   'original_language': 'en',
   'original_title': 'Go!',
   'overview': "Jack is a charismatic larrikin who has just discovered the one thing he's really good at — go-kart racing. With the support of his mentor, Patrick, an old race car driver with a secret past, and his best mates Colin and Mandy, Jack must learn to control his recklessness if he is to defeat the best drivers in Australia, including the ruthless champion Dean, and win the National title.",
   'popularity': 40.193,
   'poster_path': '/tOLC9552jBvymwsgHc3ri2SyuyD.jpg',
   'release_date': '2020-01-16',
   'title': 'Go!',
   'video': False,
   'vote_average': 6.7,
   'vote_count': 239},
  {'adult': False,
   'backdrop_path': '/9xNOiv6DZZjH7ABoUUDP0ZynouU.jpg',
   'genre_ids': [28, 80],
   'id': 495764,
   'original_language': 'en',
   'original_title': 'Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)',
   'overview': 'Harley Quinn joins forces with a singer, an assassin and a police detective to help a young girl who had a hit placed on her after she stole a rare diamond from a crime lord.',
   'popularity': 51.507,
   'poster_path': '/h4VB6m0RwcicVEZvzftYZyKXs6K.jpg',
   'release_date': '2020-02-05',
   'title': 'Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)',
   'video': False,
   'vote_average': 7,
   'vote_count': 9397},
  {'adult': False,
   'backdrop_path': '/4J1Vu6oGzt60fakP4delEPDqEhI.jpg',
   'genre_ids': [53, 28, 80],
   'id': 38700,
   'original_language': 'en',
   'original_title': 'Bad Boys for Life',
   'overview': 'Marcus and Mike are forced to confront new threats, career changes, and midlife crises as they join the newly created elite team AMMO of the Miami police department to take down the ruthless Armando Armas, the vicious leader of a Miami drug cartel.',
   'popularity': 45.808,
   'poster_path': '/y95lQLnuNKdPAzw9F9Ab8kJ80c3.jpg',
   'release_date': '2020-01-15',
   'title': 'Bad Boys for Life',
   'video': False,
   'vote_average': 7.2,
   'vote_count': 7425},
  {'adult': False,
   'backdrop_path': '/tmS9oXeMVs6njcxndDKsjJSF02H.jpg',
   'genre_ids': [18],
   'id': 552532,
   'original_language': 'en',
   'original_title': 'Charm City Kings',
   'overview': 'Mouse desperately wants to join The Midnight Clique, the infamous Baltimore dirt bike riders who rule the summertime streets. When Midnight’s leader, Blax, takes 14-year-old Mouse under his wing, Mouse soon finds himself torn between the straight-and-narrow and a road filled with fast money and violence.',
   'popularity': 40.827,
   'poster_path': '/8oiMFMarbRpcusASIX4cjVXoZKI.jpg',
   'release_date': '2020-01-27',
   'title': 'Charm City Kings',
   'video': False,
   'vote_average': 7.9,
   'vote_count': 374},
  {'adult': False,
   'backdrop_path': '/23IeumCWwWE7u2d2FDNSGPsNRbl.jpg',
   'genre_ids': [18, 27, 53],
   'id': 474764,
   'original_language': 'en',
   'original_title': 'The Lodge',
   'overview': "When a father is forced to abruptly depart for work, he leaves his children, Aidan and Mia, at their holiday home in the care of his new girlfriend, Grace. Isolated and alone, a blizzard traps them inside the lodge as terrifying events summon specters from Grace's dark past.",
   'popularity': 44.865,
   'poster_path': '/k5E8RCvDY08TntH6Ujxmq1gbOZB.jpg',
   'release_date': '2020-01-16',
   'title': 'The Lodge',
   'video': False,
   'vote_average': 6.1,
   'vote_count': 1048},
  {'adult': False,
   'backdrop_path': '/AgkGh4epJyhvs9JqSEUVABz1gJh.jpg',
   'genre_ids': [10751, 14, 12],
   'id': 448119,
   'original_language': 'en',
   'original_title': 'Dolittle',
   'overview': 'After losing his wife seven years earlier, the eccentric Dr. John Dolittle, famed doctor and veterinarian of Queen Victoria’s England, hermits himself away behind the high walls of Dolittle Manor with only his menagerie of exotic animals for company. But when the young queen falls gravely ill, a reluctant Dolittle is forced to set sail on an epic adventure to a mythical island in search of a cure, regaining his wit and courage as he crosses old adversaries and discovers wondrous creatures.',
   'popularity': 31.402,
   'poster_path': '/uoplwswBDy7gsOyrbGuKyPFoPCs.jpg',
   'release_date': '2020-01-02',
   'title': 'Dolittle',
   'video': False,
   'vote_average': 6.7,
   'vote_count': 3265},
  {'adult': False,
   'backdrop_path': '/xFxk4vnirOtUxpOEWgA1MCRfy6J.jpg',
   'genre_ids': [10751, 16, 12, 35, 14],
   'id': 508439,
   'original_language': 'en',
   'original_title': 'Onward',
   'overview': 'In a suburban fantasy world, two teenage elf brothers embark on an extraordinary quest to discover if there is still a little magic left out there.',
   'popularity': 34.096,
   'poster_path': '/f4aul3FyD3jv3v4bul1IrkWZvzq.jpg',
   'release_date': '2020-02-29',
   'title': 'Onward',
   'video': False,
   'vote_average': 7.7,
   'vote_count': 5490},
  {'adult': False,
   'backdrop_path': '/tintsaQ0WLzZsTMkTiqtMB3rfc8.jpg',
   'genre_ids': [35, 80, 28],
   'id': 522627,
   'original_language': 'en',
   'original_title': 'The Gentlemen',
   'overview': 'American expat Mickey Pearson has built a highly profitable marijuana empire in London. When word gets out that he’s looking to cash out of the business forever it triggers plots, schemes, bribery and blackmail in an attempt to steal his domain out from under him.',
   'popularity': 30.181,
   'poster_path': '/jtrhTYB7xSrJxR1vusu99nvnZ1g.jpg',
   'release_date': '2020-01-01',
   'title': 'The Gentlemen',
   'video': False,
   'vote_average': 7.7,
   'vote_count': 4844},
  {'adult': False,
   'backdrop_path': '/lOEMTu6QhwrTvQdV8kuVgMOABth.jpg',
   'genre_ids': [18],
   'id': 880956,
   'original_language': 'ja',
   'original_title': '美乳夜曲 乱れる白肌',
   'overview': 'At night, Luna after taking a bath is humming the Scottish folk song "Hometown Sky". In front of her eyes, wearing dark make-up and dressed again, there was a picture of three middle-aged men stuck on the wall ...',
   'popularity': 37.497,
   'poster_path': '/xXZfQu0Fh3BIldlo6BCH9p5rvyr.jpg',
   'release_date': '2020-02-04',
   'title': 'Beautiful Breasts Serenade: Erotic Fair Skin',
   'video': False,
   'vote_average': 0,
   'vote_count': 0},
  {'adult': False,
   'backdrop_path': '/yFRpUmsreYO5Bc0HVBTsJsHIIox.jpg',
   'genre_ids': [12, 10751, 18],
   'id': 481848,
   'original_language': 'en',
   'original_title': 'The Call of the Wild',
   'overview': 'Buck is a big-hearted dog whose blissful domestic life is turned upside down when he is suddenly uprooted from his California home and transplanted to the exotic wilds of the Yukon during the Gold Rush of the 1890s. As the newest rookie on a mail delivery dog sled team—and later its leader—Buck experiences the adventure of a lifetime, ultimately finding his true place in the world and becoming his own master.',
   'popularity': 35.767,
   'poster_path': '/33VdppGbeNxICrFUtW2WpGHvfYc.jpg',
   'release_date': '2020-02-19',
   'title': 'The Call of the Wild',
   'video': False,
   'vote_average': 7.6,
   'vote_count': 3239},
  {'adult': False,
   'backdrop_path': '/z8sNNjEXEpZNQCHCuo3QH8kK00t.jpg',
   'genre_ids': [10749],
   'id': 665142,
   'original_language': 'ko',
   'original_title': '어린 이모 3',
   'overview': "Seok-yeong has been living with his father ever since his parents got divorced when he was young. His father, Joong-nam, would always introduce his new girlfriends to Seok-yeong, but Seok-yeong didn't like running into strangers in his house. At the same time, Seok-yeong feels more comfortable with women older than him.  One day, Joong-nam says he's going to marry his new girlfriend, Gyeo-won. At a family dinner, Seok-yeong feels attracted to Gyeo-won's sister, Gyeo-woon, but he has to call her 'aunt'",
   'popularity': 49.235,
   'poster_path': '/qD7kT9LysayisTiCrdFyhZWIuK1.jpg',
   'release_date': '2020-01-02',
   'title': 'Young Aunt 3',
   'video': False,
   'vote_average': 5.3,
   'vote_count': 4},
  {'adult': False,
   'backdrop_path': '/6aVB2B2GDc4EuNinHgoBgtkuHQz.jpg',
   'genre_ids': [27, 53],
   'id': 575774,
   'original_language': 'en',
   'original_title': 'His House',
   'overview': 'After making a harrowing escape from war-torn South Sudan, a young refugee couple struggle to adjust to their new life in a small English town that has an unspeakable evil lurking beneath the surface.',
   'popularity': 47.496,
   'poster_path': '/idh2QAy5NwBRN94ScmtWrukvOgJ.jpg',
   'release_date': '2020-01-27',
   'title': 'His House',
   'video': False,
   'vote_average': 6.5,
   'vote_count': 924},
  {'adult': False,
   'backdrop_path': '/rc8WAwoTTZ5HDUDBiKhIohbl57A.jpg',
   'genre_ids': [27],
   'id': 575088,
   'original_language': 'ru',
   'original_title': 'Яга. Кошмар тёмного леса',
   'overview': 'The young family who moved to a new apartment on the outskirts of the city. The nanny hired by them for the newborn daughter quickly gained confidence. However, the older boy, Egor, talks about the frightening behavior of a woman, but his parents do not believe him. The surveillance cameras installed by the father for comfort only confirm everything is in order. Then one day, Egor, returning home, finds no trace of either the nanny or the little sister, and the parents are in a strange trance and do not even remember that they had a daughter. Then Egor, together with his friends, goes in search, during which it turns out that the nanny is an ancient Slavic demon, popularly known as Baba Yaga.',
   'popularity': 35.024,
   'poster_path': '/8m5HTXzwewlfXhtZtLlLts53YTW.jpg',
   'release_date': '2020-02-27',
   'title': 'Baba Yaga: Terror of the Dark Forest',
   'video': False,
   'vote_average': 6.1,
   'vote_count': 217},
  {'adult': False,
   'backdrop_path': '/ww7eC3BqSbFsyE5H5qMde8WkxJ2.jpg',
   'genre_ids': [27, 878, 28, 12],
   'id': 443791,
   'original_language': 'en',
   'original_title': 'Underwater',
   'overview': 'After an earthquake destroys their underwater station, six researchers must navigate two miles along the dangerous, unknown depths of the ocean floor to make it to safety in a race against time.',
   'popularity': 32.852,
   'poster_path': '/gzlbb3yeVISpQ3REd3Ga1scWGTU.jpg',
   'release_date': '2020-01-08',
   'title': 'Underwater',
   'video': False,
   'vote_average': 6.3,
   'vote_count': 2709},
  {'adult': False,
   'backdrop_path': '/tcrNJfyNEIqaBR8Ogkgnq5xQJnf.jpg',
   'genre_ids': [10749, 18],
   'id': 342470,
   'original_language': 'en',
   'original_title': 'All the Bright Places',
   'overview': 'Two teens facing personal struggles form a powerful bond as they embark on a cathartic journey chronicling the wonders of Indiana.',
   'popularity': 28.322,
   'poster_path': '/4SafxuMKQiw4reBiWKVZJpJn80I.jpg',
   'release_date': '2020-02-28',
   'title': 'All the Bright Places',
   'video': False,
   'vote_average': 7.7,
   'vote_count': 2622},
  {'adult': False,
   'backdrop_path': '/42gqGeyXh4caHP19Tqf8DMRgc7r.jpg',
   'genre_ids': [35, 10749],
   'id': 556678,
   'original_language': 'en',
   'original_title': 'Emma.',
   'overview': 'In 1800s England, a well-meaning but selfish young woman meddles in the love lives of her friends.',
   'popularity': 23.461,
   'poster_path': '/uHpHzbHLSsVmAuuGuQSpyVDZmDc.jpg',
   'release_date': '2020-02-13',
   'title': 'Emma.',
   'video': False,
   'vote_average': 7,
   'vote_count': 1511},
  {'adult': False,
   'backdrop_path': '/sizHX5VbwlBihaathTQHVGk1jdi.jpg',
   'genre_ids': [878, 18, 28],
   'id': 514207,
   'original_language': 'ru',
   'original_title': 'Вторжение',
   'overview': 'Two years after the fall of the alien ship, the life of a young woman from Moscow has been changed forever. Her growing powers are now at the focus of both human and celestial investigation: an alien force takes an interest in her, and will stop short of nothing, including an invasion. Can love and compassion save humanity, when faced with a much greater and more demanding test this time?',
   'popularity': 23.703,
   'poster_path': '/dqKqzcdhtJwOhjqe89RTURqILtl.jpg',
   'release_date': '2020-01-01',
   'title': 'Invasion',
   'video': False,
   'vote_average': 6.9,
   'vote_count': 694},
  {'adult': False,
   'backdrop_path': '/6mKAKhj8POVGqV1GsroS5mGIUe9.jpg',
   'genre_ids': [14, 28, 12],
   'id': 666750,
   'original_language': 'en',
   'original_title': 'Dragonheart: Vengeance',
   'overview': 'Lukas, a young farmer whose family is killed by savage raiders in the countryside, sets out on an epic quest for revenge, forming an unlikely trio with a majestic dragon and a swashbuckling, sword-fighting mercenary, Darius.',
   'popularity': 25.952,
   'poster_path': '/qs6gz6atyQcAvqC6qZaslOjliUG.jpg',
   'release_date': '2020-02-04',
   'title': 'Dragonheart: Vengeance',
   'video': False,
   'vote_average': 6.9,
   'vote_count': 283}],
 'total_pages': 273,
 'total_results': 5445}

In [22]:
df = pd.DataFrame(data2['results'])

In [24]:
df

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,None,[18],677118,ko,오르가즘 특강 2,"Yuner, Liu Ren, and Zhou Xian are college girl...",91.246,/gYSJi5avO0RmzrX9ZbKwM7ZMkng.jpg,2020-02-20,Orgasm Lecture 2,False,10.0,1
1,False,/stmYfCUGd8Iy6kAMBr6AmWqx8Bq.jpg,"[28, 878, 35, 10751]",454626,en,Sonic the Hedgehog,"Powered with incredible speed, Sonic The Hedge...",71.239,/aQvJ5WPzZgYVDrxLX4R6cLJCEaQ.jpg,2020-02-12,Sonic the Hedgehog,False,7.4,8658
2,False,/hRgQVdKh65nFiy2l7KhfWo7DHof.jpg,[10751],520765,en,Go!,Jack is a charismatic larrikin who has just di...,40.193,/tOLC9552jBvymwsgHc3ri2SyuyD.jpg,2020-01-16,Go!,False,6.7,239
3,False,/9xNOiv6DZZjH7ABoUUDP0ZynouU.jpg,"[28, 80]",495764,en,Birds of Prey (and the Fantabulous Emancipatio...,"Harley Quinn joins forces with a singer, an as...",51.507,/h4VB6m0RwcicVEZvzftYZyKXs6K.jpg,2020-02-05,Birds of Prey (and the Fantabulous Emancipatio...,False,7.0,9397
4,False,/4J1Vu6oGzt60fakP4delEPDqEhI.jpg,"[53, 28, 80]",38700,en,Bad Boys for Life,Marcus and Mike are forced to confront new thr...,45.808,/y95lQLnuNKdPAzw9F9Ab8kJ80c3.jpg,2020-01-15,Bad Boys for Life,False,7.2,7425
5,False,/tmS9oXeMVs6njcxndDKsjJSF02H.jpg,[18],552532,en,Charm City Kings,Mouse desperately wants to join The Midnight C...,40.827,/8oiMFMarbRpcusASIX4cjVXoZKI.jpg,2020-01-27,Charm City Kings,False,7.9,374
6,False,/23IeumCWwWE7u2d2FDNSGPsNRbl.jpg,"[18, 27, 53]",474764,en,The Lodge,When a father is forced to abruptly depart for...,44.865,/k5E8RCvDY08TntH6Ujxmq1gbOZB.jpg,2020-01-16,The Lodge,False,6.1,1048
7,False,/AgkGh4epJyhvs9JqSEUVABz1gJh.jpg,"[10751, 14, 12]",448119,en,Dolittle,"After losing his wife seven years earlier, the...",31.402,/uoplwswBDy7gsOyrbGuKyPFoPCs.jpg,2020-01-02,Dolittle,False,6.7,3265
8,False,/xFxk4vnirOtUxpOEWgA1MCRfy6J.jpg,"[10751, 16, 12, 35, 14]",508439,en,Onward,"In a suburban fantasy world, two teenage elf b...",34.096,/f4aul3FyD3jv3v4bul1IrkWZvzq.jpg,2020-02-29,Onward,False,7.7,5490
9,False,/tintsaQ0WLzZsTMkTiqtMB3rfc8.jpg,"[35, 80, 28]",522627,en,The Gentlemen,American expat Mickey Pearson has built a high...,30.181,/jtrhTYB7xSrJxR1vusu99nvnZ1g.jpg,2020-01-01,The Gentlemen,False,7.7,4844
10,False,/lOEMTu6QhwrTvQdV8kuVgMOABth.jpg,[18],880956,ja,美乳夜曲 乱れる白肌,"At night, Luna after taking a bath is humming ...",37.497,/xXZfQu0Fh3BIldlo6BCH9p5rvyr.jpg,2020-02-04,Beautiful Breasts Serenade: Erotic Fair Skin,False,0.0,0
11,False,/yFRpUmsreYO5Bc0HVBTsJsHIIox.jpg,"[12, 10751, 18]",481848,en,The Call of the Wild,Buck is a big-hearted dog whose blissful domes...,35.767,/33VdppGbeNxICrFUtW2WpGHvfYc.jpg,2020-02-19,The Call of the Wild,False,7.6,3239
12,False,/z8sNNjEXEpZNQCHCuo3QH8kK00t.jpg,[10749],665142,ko,어린 이모 3,Seok-yeong has been living with his father eve...,49.235,/qD7kT9LysayisTiCrdFyhZWIuK1.jpg,2020-01-02,Young Aunt 3,False,5.3,4
13,False,/6aVB2B2GDc4EuNinHgoBgtkuHQz.jpg,"[27, 53]",575774,en,His House,After making a harrowing escape from war-torn ...,47.496,/idh2QAy5NwBRN94ScmtWrukvOgJ.jpg,2020-01-27,His House,False,6.5,924
14,False,/rc8WAwoTTZ5HDUDBiKhIohbl57A.jpg,[27],575088,ru,Яга. Кошмар тёмного леса,The young family who moved to a new apartment ...,35.024,/8m5HTXzwewlfXhtZtLlLts53YTW.jpg,2020-02-27,Baba Yaga: Terror of the Dark Forest,False,6.1,217
15,False,/ww7eC3BqSbFsyE5H5qMde8WkxJ2.jpg,"[27, 878, 28, 12]",443791,en,Underwater,After an earthquake destroys their underwater ...,32.852,/gzlbb3yeVISpQ3REd3Ga1scWGTU.jpg,2020-01-08,Underwater,False,6.3,2709
16,False,/tcrNJfyNEIqaBR8Ogkgnq5xQJnf.jpg,"[10749, 18]",342470,en,All the Bright Places,Two teens facing personal struggles form a pow...,28.322,/4SafxuMKQiw4reBiWKVZJpJn80I.jpg,2020-02-28,All the Bright Places,False,7.7,2622
17,False,/42gqGeyXh4caHP19Tqf8DMRgc7r.jpg,"[35, 10749]",556678,en,Emma.,"In 1800s England, a well-meaning but selfish y...",23.461,/uHpHzbHLSsVmAuuGuQSpyVDZmDc.jpg,2020-02-13,Emma.,False,7.0,1511
18,False,/sizHX5VbwlBihaathTQHVGk1jdi.jpg,"[878, 18, 28]",514207,ru,Вторжение,"Two years after the fall of the alien ship, th...",23.703,/dqKqzcdhtJwOhjqe89RTURqILtl.jpg,2020-01-01,Invasion,False,6.9,694
19,False,/6mKAKhj8POVGqV1GsroS5mGIUe9.jpg,"[14, 28, 12]",666750,en,Dragonheart: Vengeance,"Lukas, a young farmer whose family is killed b...",25.952,/qs6gz6atyQcAvqC6qZaslOjliUG.jpg,2020-02-04,Dragonheart: Vengeance,False,6.9,283

##  Importing and Saving the Movies Dataset (Best Practice)

6. __API-Request__ (movie module): Load all available information for the movies with movie id = [__299534, 19995, 140607, 299536, 597, 135397, 420818, 24428, 168259, 99861, 284054, 12445, 181808, 330457, 351286, 109445, 321612, 260513__] into a Pandas DataFrame and __save the dataset in a local json file__.

In [26]:
movie_id = [299534, 19995, 140607, 299536, 597, 135397, 420818, 24428, 168259, 99861, 284054, 12445, 181808, 330457, 351286, 109445, 321612, 260513]

In [27]:
url3 = "https://api.themoviedb.org/3/movie/{}?{}"

In [28]:
json_list = []
for movie in movie_id:
    url = url3.format(movie,api_key)
    r = requests.get(url)
    if r.status_code != 200:
        continue
    else:
        data = r.json()
        json_list.append(data)
        df = pd.DataFrame(json_list)

In [29]:
df

,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",356000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",https://www.marvel.com/movies/avengers-endgame,299534,tt4154796,en,Avengers: Endgame,After the devastating events of Avengers: Infi...,101.337,/or06FN3Dka5tukK1e9sl16pB3iy.jpg,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...","[{'iso_3166_1': 'US', 'name': 'United States o...",2019-04-24,2794731755,181,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Avenge the fallen.,Avengers: Endgame,False,8.266,23090
1,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,"{'id': 87096, 'name': 'Avatar Collection', 'po...",237000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",https://www.avatar.com/movies/avatar,19995,tt0499549,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",219.009,/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg,"[{'id': 444, 'logo_path': None, 'name': 'Dune ...","[{'iso_3166_1': 'US', 'name': 'United States o...",2009-12-15,2923706026,162,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Enter the world of Pandora.,Avatar,False,7.569,29040
2,False,/8BTsTfln4jlQrLXUBquXJ0ASQy9.jpg,"{'id': 10, 'name': 'Star Wars Collection', 'po...",245000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.starwars.com/films/star-wars-episod...,140607,tt2488496,en,Star Wars: The Force Awakens,Thirty years after defeating the Galactic Empi...,64.888,/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg,"[{'id': 1, 'logo_path': '/o86DbpburjxrqAzEDhXZ...","[{'iso_3166_1': 'US', 'name': 'United States o...",2015-12-15,2068223624,136,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Every generation has a story.,Star Wars: The Force Awakens,False,7.300,17979
3,False,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",https://www.marvel.com/movies/avengers-infinit...,299536,tt4154756,en,Avengers: Infinity War,As the Avengers and their allies have continue...,205.036,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...","[{'iso_3166_1': 'US', 'name': 'United States o...",2018-04-25,2046239637,149,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,An entire universe. Once and for all.,Avengers: Infinity War,False,8.263,26811
4,False,/rzdPqYx7Um4FUZeD8wpXqjAUcEm.jpg,None,200000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",https://www.paramountmovies.com/movies/titanic,597,tt0120338,en,Titanic,101-year-old Rose DeWitt Bukater tells the sto...,108.782,/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg,"[{'id': 4, 'logo_path': '/gz66EfNoYPqHTYI4q9UE...","[{'iso_3166_1': 'US', 'name': 'United States o...",1997-11-18,2264162353,194,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Nothing on Earth could come between them.,Titanic,False,7.892,22838
5,False,/aIGIYJTyOkEVUmEd3z5x6diYsFx.jpg,"{'id': 328, 'name': 'Jurassic Park Collection'...",150000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.jurassicworld.com/,135397,tt0369610,en,Jurassic World,Twenty-two years after the events of Jurassic ...,79.861,/A0LZHXUzo5C60Oahvt7VxvwuzHw.jpg,"[{'id': 56, 'logo_path': '/cEaxANEisCqeEoRvODv...","[{'iso_3166_1': 'US', 'name': 'United States o...",2015-06-12,1671537444,124,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,The park is open.,Jurassic World,False,6.680,19031
6,False,/1TUg5pO1VZ4B0Q1amk3OlXvlpXV.jpg,"{'id': 762512, 'name': 'The Lion King (Reboot)...",260000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",https://movies.disney.com/the-lion-king-2019,420818,tt6105098,en,The Lion King,"Simba idolizes his father, King Mufasa, and ta...",60.210,/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg,"[{'id': 2, 'logo_path': '/wdrCwmRnLFJhEoH8GSfy...","[{'iso_3166_1': 'US', 'name': 'United States o...",2019-07-12,1663075401,118,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,The King has Returned.,The Lion King,False,7.129,9090
7,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",https://www.marvel.com/movies/the-avengers,24428,tt0848228,en,The Avengers,When an unexpected enemy emerges and threatens...,121.956,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...","[{'iso_3166_1': 'US', 'name': 'United States o...",2012-04-25,1518815515,143,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Some assembly required.,The Avengers,False,7.707,28544
8,False,/cHkhb5A4gQRK6zs6Pv7zorHs8Nk.jpg,"{'id': 9485, 'name': 'The Fast and the Furious...",190000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",https://www.thefastsaga.com/fast-saga/ff7,168259,tt2820852,en,Furious 7,Deckard Shaw seeks revenge against Dominic Tor...,174.878,/ktofZ9Htrjiy0P6LEowsDaxd3Ri.jpg,"[{'id': 333, 'logo_path': '/5xUJfzPZ8jWJUDzYtI...","[{'iso_3166_1': 'US', 'name': 'United States o...",2015-04-01,1515341399,137,"[{'english_name': 'Arabic', 'iso_639_1': 'ar',...",Released,Vengeance hits home,Furious 7,False,7.232,9693
9,False,/6YwkGolwdOMNpbTOmLjoehlVWs5.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",365000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://marvel.com/movies/movie/193/avengers_ag...,99861,tt2395427,en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,88.098,/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...","[{'iso_3166_1': 'US', 'name': 'United States o...",2015-04-22,1405403694,141,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,A New Age Has Come.,Avengers: Age of Ultron,False,7.280,21240
10,False,/b6ZJZHUdMEFECvGiDpJjlfUWela.jpg,"{'id': 529892, 'name': 'Black Panther Collecti...",200000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",https://www.marvel.com/movies/black-panther,284054,tt1825683,en,Black Panther,"King T'Challa returns home to the reclusive, t...",53.216,/uxzzxijgPIY7slzFvMotPv8wjKA.jpg,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...","[{'iso_3166_1': 'US', 'name': 'United States o...",2018-02-13,1349926083,135,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Long live the king.,Black Panther,False,7.393,20593
11,False,/n5A7brJCjejceZmHyujwUTVgQNC.jpg,"{'id': 1241, 'name': 'Harry Potter Collection'...",125000000,"[{'id': 14, 'name': 'Fantasy'}, {'id': 12, 'na...",https://www.warnerbros.com/movies/harry-potter...,12445,tt1201607,en,Harry Potter and the Deathly Hallows: Part 2,"Harry, Ron and Hermione continue their quest t...",112.478,/c54HpQmuwXjHq2C9wmoACjxoom3.jpg,"[{'id': 174, 'logo_path': '/IuAlhI9eVC9Z8UQWOI...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",2011-07-07,1341511219,130,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,It all ends here.,Harry Potter and the Deathly Hallows: Part 2,False,8.100,18678
12,False,/5Iw7zQTHVRBOYpA0V6z0yypOPZh.jpg,"{'id': 10, 'name': 'Star Wars Collection', 'po...",200000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",https://www.starwars.com/films/star-wars-episo...,181808,tt2527336,en,Star Wars: The Last Jedi,Rey develops her newly discovered abilities wi...,65.190,/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg,"[{'id': 1, 'logo_path': '/o86DbpburjxrqAzEDhXZ...","[{'iso_3166_1': 'US', 'name': 'United States o...",2017-12-13,1332698830,152,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Darkness rises... and light to meet it,Star Wars: The Last Jedi,False,6.837,13954
13,False,/xJWPZIYOEFIjZpBL7SVBGnzRYXp.jpg,"{'id': 386382, 'name': 'Frozen Collection', 'p...",150000000,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",https://movies.disney.com/frozen-2,330457,tt4520988,en,Frozen II,"Elsa, Anna, Kristoff and Olaf head far into th...",85.463,/mINJaa34MtknCYl5AjtNJzWj8cD.jpg,"[{'id': 2, 'logo_path': '/wdrCwmRnLFJhEoH8GSfy...","[{'iso_3166_1': 'US', 'name': 'United States o...",2019-11-20,1450026933,103,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,The past is not what it seems.,Frozen II,False,7.276,8830
14,False,/3s9O5af2xWKWR5JzP2iJZpZeQQg.jpg,"{'id': 328, 'name': 'Jurassic Park Collection'...",170000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.jurassicworld.com,351286,tt4881806,en,Jurassic World: Fallen Kingdom,When the island's dormant volcano begins roari...,56.219,/2CQ53CuWD1KdlOkEWhJcEVjqKn4.jpg,"[{'id': 56, 'logo_path': '/cEaxANEisCqeEoRvODv...","[{'iso_3166_1': 'US', 'name': 'United States o...",2018-06-22,1310466296,129,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,The park is gone.,Jurassic World: Fallen Kingdom,False,6.549,10134
15,False,/fydUcbkqLyESCFa9U5XKqi8dIVj.jpg,"{'id': 386382, 'name': 'Frozen Collection', 'p...",150000000,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",http://movies.disney.com/frozen,109445,tt2294629,en,Frozen,Young princess Anna of Arendelle dreams about ...,70.892,/kgwjIb2JDHRhNk13lmSxiClFjVk.jpg,"[{'id': 2, 'logo_path': '/wdrCwmRnLFJhEoH8GSfy...","[{'iso_3166_1': 'US', 'name': 'United States o...",2013-11-20,1274219009,102,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Only the act of true love will thaw a frozen h...,Frozen,False,7.200,15153
16,False,/m3tdSyl11fhgXPDSEt3aBctTqGP.jpg,None,160000000,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",http://movies.disney.com/beauty-and-the-beast-...,321612,tt2771200,en,Beauty and the Beast,A live-action adaptation of Disney's version o...,45.491,/hKegSKIDep2ewJWPUQD7u0KqFIp.jpg,"[{'id': 2, 'logo_path': '/wdrCwmRnLFJhEoH8GSfy...","[{'iso_3166_1': 'US', 'name': 'United States o...",2017-03-16,1263521126,129,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Be our guest.,Beauty and the Beast,False,6.963,14646
17,False,/mabuNsGJgRuCTuGqjFkWe1xdu19.jpg,"{'id': 468222, 'name': 'The Incredibles Collec...",200000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",https://movies.disney.com/incredibles-2,260513,tt3606756,en,Incredibles 2,Elastigirl springs into action to save the day...,52.103,/9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg,"[{'id': 2, 'logo_path': '/wdrCwmRnLFJhEoH8GSfy...","[{'iso_3166_1': 'US', 'name': 'United States o...",2018-06-14,1242805359,118,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Back to work.,Incredibles 2,False,7.487,11746